export const strings = {
  appName: 'Networkr',
  welcome: 'Welcome to Networkr',
  signin: 'Sign In',
  signup: 'Sign Up',
  welcomedescription: 'Discover Professionals Around You',
  or: 'or',
  connect: 'connect',
  linkedIn: 'with LinkedIn',
  signlinkedIn: 'with LinkedIn',
  email: 'Email',
  enteremail: 'Enter your email',
  name: 'Name',
  entername: 'Enter your full name',
  password: 'Password',
  enterpassword: 'Enter a new password',
  forgotpassword: 'Forgot Password?',
  successfullRegistration: 'Account successfully registered',
  emailrequired: 'Email is required.',
  emailnotvalid: 'Email is not valid.',
  passwordrequired: 'Password is required.',
  passwordlength: 'Password length should be atleast 6 characters',
  namerequired: 'Name is Required',
  education: 'Education',
  experience: 'Experience',
  about: 'About',
  enterabout: 'Write about yourself',
  lookingfor: `What you're looking for?`,
  careeradvice: 'Career Advice',
  professional: 'Expand Professional Network',
  mentor: 'Mentoring Others',
  goodat: "What you're good at?",
  havebeenselected: 'skills have been selected',
  hasbeenselected: 'skill has been selected',
  selectskills: 'Select your skills',
  institue: 'Institute',
  institueplaceholder: 'University or College',
  degree: 'Degree',
  degreeplaceholder: 'BS Computer Science',
  startdate: 'Start Date',
  enddate: 'End Date',
  inprogress: 'In Progress',
  professionalsummary: 'Professional Summary',
  addeducation: 'Add Education',
  next: 'Next',
  save: 'Save',
  instituerequired: 'Institute is Required',
  degreerequired: 'Degree is Required',
  startdaterequired: 'Start date is Required',
  enddaterequired: 'End date is Required',
  addexperience: 'Add Experience',
  title: 'Title',
  titleplaceholder: 'Sales Manager',
  titlerequired: 'Title is Required',
  companyname: 'Company name',
  companyplaceholder: 'Microsoft',
  companynamerequired: 'Company name is Required',
  currentlyworking: 'I am currently working in this role',
  present: 'Present',
  purposerequired: "Select what you're looking for",
  oneskillrequired: 'Please select at least One Skill.',
  educationrequired: 'Please add at least One Education.',
  newopportunity: 'Looking for new opportunity?',
  profileupdated: 'Profile Updated Successfully',
  logout: 'LogOut',
  mynetwork: 'My Network',
  pendingRequest: 'Pending Requests',
  norequest: 'No New Request Found.',
  noperson: 'No Person connected.',
  remove: 'Remove',
};
